spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myegg?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: myegg
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mybatis/*.xml
  type-aliases-package: com.myegg.pojo

