spring:
  datasource:
    url: jdbc:mysql://47.105.194.10:3306/myegg?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: Abc123!_
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mybatis/*.xml
  type-aliases-package: com.myegg.pojo

